# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'YabaSnashiro' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'Firebase/Firestore'
  pod 'Firebase/Messaging'
  pod 'Firebase/RemoteConfig'
  pod 'GoogleSignIn'
  pod 'FirebaseCrashlytics'
  pod 'Kingfisher', '~> 7.0'

  # Pods for uoyabause

  target 'YabaSnashiro-Lite' do
    inherit! :search_paths
    pod 'Firebase/Core'
    pod 'Firebase/Auth'
    pod 'Firebase/Storage'
    pod 'Firebase/Database'
    pod 'Firebase/Firestore'
    pod 'Firebase/Messaging'
    pod 'Firebase/RemoteConfig'
    pod 'GoogleSignIn'
    pod 'FirebaseCrashlytics'
    pod 'Kingfisher', '~> 7.0'
    pod 'Google-Mobile-Ads-SDK'
    end

  target 'YabaSnashiroTests' do
    inherit! :search_paths
    pod 'Firebase/Core'
    pod 'Firebase/Auth'
    pod 'Firebase/Storage'
    pod 'Firebase/Database'
    pod 'Firebase/Firestore'
    pod 'Firebase/Messaging'
    pod 'Firebase/RemoteConfig'
    pod 'GoogleSignIn'
    pod 'FirebaseCrashlytics'
    pod 'Kingfisher', '~> 7.0'
  end

  target 'YabaSnashiroUITests' do
    inherit! :search_paths
    pod 'Firebase/Core'
    pod 'Firebase/Storage'
    pod 'Firebase/Auth'
    pod 'Firebase/Database'
    pod 'Firebase/Firestore'
    pod 'Firebase/Messaging'
    pod 'Firebase/RemoteConfig'
    pod 'GoogleSignIn'
    pod 'FirebaseCrashlytics'
    pod 'Kingfisher', '~> 7.0'
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'BoringSSL-GRPC'
      target.source_build_phase.files.each do |file|
        if file.settings && file.settings['COMPILER_FLAGS']
          flags = file.settings['COMPILER_FLAGS'].split
          flags.reject! { |flag| flag == '-GCC_WARN_INHIBIT_ALL_WARNINGS' }
          file.settings['COMPILER_FLAGS'] = flags.join(' ')
        end
      end
    end
  end
end
